version: '3.8'

services:
  # TODO: figure out how to templatize these service configs
  irys-1:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: irys-1
    restart: unless-stopped
    networks:
      app_network:
        ipv4_address: 172.20.0.2
    ports:
      - "8080:8080" # host port : container port
    environment:
      - RUST_LOG=debug
    volumes:
      - ./configs/irys-1.toml:/app/config.toml
      - ../target/debug-release/irys:/app/irys
    # for ufw/iptables
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "
        chmod +x /app/irys

        ufw default deny incoming
        ufw allow 8080
        ufw allow 9009
        ufw allow 9010        
        ufw --force enable
        
        exec /app/irys"

  irys-2:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: irys-2
    restart: unless-stopped
    networks:
      app_network:
        ipv4_address: 172.20.0.3
    ports:
      - "8081:8080" # host port : container port
    environment:
      - RUST_LOG=debug
    volumes:
      - ./configs/irys-1.toml:/app/config.toml
      - ../target/debug-release/irys:/app/irys
    # for ufw/iptables
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "
        chmod +x /app/irys
        
        ufw default deny incoming
        ufw allow 8080
        ufw allow 9009
        ufw allow 9010        
        ufw --force enable
        
        exec /app/irys"

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
